##############################################
# !!! Datei umbenennen !!!              ######
# secrets_copy.toml -> secrets.toml     ######
##############################################

[webdav]
base_url = "https://drive.switch.ch/remote.php/dav/files/your_username/"
username = "your_username@org.ch"
password = "your_secure_password"

[auth]
teacher_code = "GEHEIMCODE2025"
cookie_key = "your_generated_random_key_here_min_32_chars"